package idv.module.po;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class Product implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Fri Aug 21 14:07:38 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.en_name
     *
     * @mbg.generated Fri Aug 21 14:07:38 CST 2020
     */
    private String enName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.zh_name
     *
     * @mbg.generated Fri Aug 21 14:07:38 CST 2020
     */
    private String zhName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Fri Aug 21 14:07:38 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.release_date
     *
     * @mbg.generated Fri Aug 21 14:07:38 CST 2020
     */
    private LocalDate releaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.edit_date
     *
     * @mbg.generated Fri Aug 21 14:07:38 CST 2020
     */
    private LocalDateTime editDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Fri Aug 21 14:07:38 CST 2020
     */
    private static final long serialVersionUID = 1L;
}